services:
  - type: web
    name: xtopus
    runtime: docker
    region: frankfurt
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8000
      - key: ENVIRONMENT
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: FIREBASE_STORAGE_BUCKET
        value: giteksolhub-project.firebasestorage.app
      - key: EMAILJS_SERVICE_ID
        value: service_78wp8b9
      - key: EMAILJS_TEMPLATE_ID
        value: template_06fjijo
      - key: EMAILJS_PUBLIC_KEY
        value: VGj6eL5SaKXRW2fIi
      - key: EMAILJS_PRIVATE_KEY
        value: oogPO4beeg5UpY1k-Y-UA